name: RTW CI

on: [push]

jobs:
  build_linux:
    name: build ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting (cargo fmt)
      run: rustfmt --check src/*.rs
    - name: Run linting check (clippy)
      run: cargo clippy

  build_mac:
    name: build macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build_windows:
    name: build windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
