name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting (cargo fmt)
      run: cargo fmt -- --check
    - name: Run linting check (clippy)
      run: cargo clippy
